### ISSUE TITLE
Make it easier to package this to GNU/Linux distributions other then Arch Linux & Debian

### ISSUE THREAD

**Issue by doronbehar** [kanehekili/VideoCut#32]
Hello,

This application seems interesting, though I have no idea how to install it. I have packaged [~85 packages for NixOS](https://repology.org/projects/c/?maintainer=me%40doronbehar.com&inrepo=nix_unstable), many of which are Python packages, and this repository, seems to be written in Python, doesn't adhere to any standard, and I have no idea where to start when building it - there is no `setup.py`, no `pyproject.toml` etc.. I found some `Makefile`s in non-standard locations, but I didn't understand what they are for...

I may be able to help with that after I'll put my mind to it, but in the meantime it'd be great if you'll show interest in fixing this.

**Comment by kanehekili** [comment]
Thanks for the notion. Since I'm not able to support every Linux distro, I created an "install.sh" file, which should help to install videocut on any "foreign" distro. The names of the dependencies of your distro are not known to me.  The `Makefile`is used to compile the muxer, which is using the FFmpeg libraries to improve the cutting. Due to the mixture of "python" and "C" I'm not sure how to provide general build data otherwise.  The "generic install" provides binaries for the muxer - let me know if they don't work with NixOS. Reading about NixOS, I would be very interested in learning about consistent package builds...

**Comment by doronbehar** [comment]
Read [this official packaging guide](https://packaging.python.org/en/latest/), and in particular, for such a C compiled extension, [this guide seems good to me](https://realpython.com/build-python-c-extension-module/#packaging-your-python-c-extension-module).

Your `install.sh` is not compatible with NixOS, because we don't allow binaries to be installed in `/usr/`. Read more about our concepts on [our website](https://nixos.org/guides/how-nix-works). Even if I had changed the paths there there to something we can use, I'd never package this software using that script, when it should be much more easy to install it if it only had a `setup.py`.

To begin working like every other Python programmer out there on the Internet, try to write a `setup.py` file, and test whether you can install your Python package with `pip install .`, or `python setup.py install`. It is likely that this would make most of the work for many other Linux distribution to distribute your software.

**Comment by kanehekili** [comment]
To be honest: I'm doing this in my free time, besides getting my kids up and supporting a "sportverein". This is open source. Place your changes or get lost.
