### ISSUE TITLE
[question] Where in the source do you set the output audio and video bitrates?

### ISSUE THREAD

**Issue by rado84-github** [kanehekili/VideoCut#33]
The precise cut is good but it compresses the output audio and video and I wanna change that. Since there's nothing about that in the config file, where in the source code do you set the ffmpeg audio and video bitrate for output?

**Comment by kanehekili** [comment]
Good question. I try to get as close to the original video bit rate as possible, using the "internal remux " converter. But I do **not** compress audio, **it is always copied**.  So I accept the complaint of possibly reducing the video bandwidth, but no code is hampering with audio. 
Thanks for your input, because the video quality on precise cut should be configurable. I'll extend that feature.

**Comment by rado84-github** [comment]
> Good question. I try to get as close to the original video bit rate as possible, using the "internal remux " converter. But I do **not** compress audio, **it is always copied**. So I accept the complaint of possibly reducing the video bandwidth, but no code is hampering with audio. Thanks for your input, because the video quality on precise cut should be configurable. I'll extend that feature.

I can show you how I make an extraction from a whole episode which I converted from H264 to H265 with NVENC and to ~5000 kbps video bitrate & 640 kbps audio bitrate. After the extraction is finished, the video bitrate is somewhat close to the original but the audio ALWAYS ends up at 122 kbps, so the audio bitrate must be specified somewhere, I doubt that ffmpeg or the program would change it themselves and to such a specific bitrate.

I also tried using the other option - remux, which is supposed to be faster and completely lossless but it's bugged and always misses a few scenes. I had a lot of trouble extracting this specific scene from "The Flash": https://vtube7.com/watch/barry-allen-running-on-water-like-jizz-us-christ_wI2EQIqJ71UHJyS.html With the supposedly lossless remux option the video always ended up frozen frame 10 seconds before the end of the video where The Flash gets out of the water. I had to resort to LosslessCut to get the whole scene without frozen frames.
I found a workaround for that (extract the audio before extracting the video fragment; cut the audio to video output length and then put the audio back in the newly extracted video), altough I'd prefer to avoid it, if possible.

**Comment by kanehekili** [comment]
Thanks for the feedback. The remux demuxer is indeed lossless, but only in the "fast" mode, since then the packages are only copied, not de- and encoded.  I assume that you experience the "freeze" when you re-encode (which is not lossless). Since audio is always copied, I try to sync audio and video - if timestamps don't match - depending on the codecs - I've observed those freezes as well.
It looks like a design flaw to me (not re-encoding audio when video is) and will look into it. Furthermore, I'll verify my audio buffer calculation, I've might make some wrong assumptions there. 
Note that the fast cut will not work satisfactorily with h265, since its GOP size is far too large to find any IDR frames close to the designated cut point. Have you considered cutting the h264 before converting it to h265?

**Update**

I've downloaded your link (using my ytdownloader on this site) and analyzed it: 
Video: 5240 Kb/s, audio AAC-LC 128kb/s - so whatever you did, the meager bitrate of 128 Kb/s will not get better by upscaling it. 
Cutting it resolved to: Video: 5917 Kb/s and audio 128 Kb/s  -the audio part - but the I-Frame shifted for one frame. That is wrong and I'll look into it

**Comment by rado84-github** [comment]
That site converts the videos after uploading and I suspect the audio being 128 kbps is the result of that conversion. The whole episode from which I extracted the scene has 3086 kbps video bitrate and 640 kbps audio bitrate.

As for "cutting the h264 before converting it to h265" - that's no longer an option since I converted these long ago and now I'm only extracting parts of them whenever I need.
